Correct protobuf checksum
Fixes the following build issue:

 ERROR: protobuf-3.0.0-r0 do_fetch: Fetcher failure for URL: 'https://github.com/google/protobuf/archive/v3.0.0.tar.gz;downloadfilename=protobuf-3.0.0.tar.gz'. Checksum mismatch!
 File: '/data/dwrobel1/projects/rdkv/rpi-cobalt-1/build-raspberrypirdkhybrefapp/../downloads/protobuf-3.0.0.tar.gz' has md5 checksum 41f2934b451a82115ccc4aa1f9b156f2 when d4f6ca65aadc6310b3872ee421e79fa6 was expected
 File: '/data/dwrobel1/projects/rdkv/rpi-cobalt-1/build-raspberrypirdkhybrefapp/../downloads/protobuf-3.0.0.tar.gz' has sha256 checksum 44e36eee53a7bc8b88935b105c8e2773f6ae9f89e3f25e95f93c4bcac908bb98 when f5b3563f118f1d3d6e001705fa7082e8fc3bda50038ac3dff787650795734146 was expected
 If this change is expected (e.g. you have upgraded to a new version without updating the checksums) then you can use these lines within the recipe:
 SRC_URI[md5sum] = "41f2934b451a82115ccc4aa1f9b156f2"
 SRC_URI[sha256sum] = "44e36eee53a7bc8b88935b105c8e2773f6ae9f89e3f25e95f93c4bcac908bb98"
 Otherwise you should retry the download and/or check with upstream to determine if the file has become corrupted or otherwise unexpectedly modified.

Change-Id: I05864bb9f71606e55be78129820ca9f32f5198c9